### ISSUE TITLE
UUIDs on customer and inventory objects

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#10]
Use uuid gem to add uuids to customer and inventory objects.

**Comment by josephbridgwaterrowe** [comment]
I don't think we need this on all objects, just those as necessary, for instance customer and inventory items.

**Comment by michaelachrisco** [comment]
Sounds good. Let me know if any other objects are needed.

**Comment by michaelachrisco** [comment]
I am looking at two different gems for this task. There is the default gem we were discussing earlier
```gem uuid```
and then I found this gem:
https://github.com/jashmenn/activeuuid
```gem activeuuid```
I believe both do similar operations but uuid uses a string and activeuuid uses bytes. Thoughts?

**Comment by josephbridgwaterrowe** [comment]
I prefer the 32 character UUID's to be honest, does activeuuid do those?

**Comment by michaelachrisco** [comment]
It looks like from https://github.com/jashmenn/activeuuid#use-it that the gem will store the UUID as 128 bytes but can convert to 36 char(with 4 "-", so 32 char) version.

**Comment by josephbridgwaterrowe** [comment]
I want to store the UUID as a readable value in the database and given that storage is free and infinite the storage benefits don't really appeal to me :smile:

**Comment by michaelachrisco** [comment]
Can do. Just another option should the db become very slow/big/bulky :8ball:

**Comment by josephbridgwaterrowe** [comment]
Sure. But to be honest I think that one reference column would be the least of our problems :wink:

**Comment by josephbridgwaterrowe** [comment]
Closing this as I don't think its within the purview of this project.
