### ISSUE TITLE
Old plissken reference

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#118]
@josephbridgwaterrowe I am deleting some old libraries and I came across this fork we worked on about 4-5 years ago. https://github.com/westernmilling/gman-services/blob/master/Gemfile#L18

Thought I would let you know before I delete the library. If you would like, I can give western milling sole ownership over it (no-one else is using it) or you can fork my solution. Or better yet remove it completely 👍 whichever is your choice.

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco thanks for your message... I hope you're well.

I'm no longer responsible for gman-services so your question would be better addressed by @cracell 

Eric, I'll let you decide how you want to proceed.
