### ISSUE TITLE
Add coveralls

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [westernmilling/gman-services#15]

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco, Let me know if I need to add access to the site.

**Comment by michaelachrisco** [comment]
Looks like I will. I am on the site and none of the WesternMiling repos are showing up.

**Comment by josephbridgwaterrowe** [comment]
Can you try again... I added the repo to coveralls, but I didn't see any user access control. But I may just be blind. :wink:

**Comment by michaelachrisco** [comment]
Ok I see coveralls. I will add the gem in a bit.
