### ISSUE TITLE
Update Driver Columns

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#27]
Payroll expects:
```Ruby
#<Driver id: nil, 
active: true, 
external_driver_id: nil, 
department_id: nil, 
driver_type: nil, 
first_name: nil, 
last_name: nil, 
sub_hauler_flag: false, 
payroll_id_override: nil, 
created_at: nil, 
updated_at: nil, 
deleted_at: nil> 
```

Update Driver to reflect.

**Comment by michaelachrisco** [comment]
reference: https://github.com/westernmilling/payroll-app/issues/52

**Comment by michaelachrisco** [comment]
Current DDL:
```
CREATE TABLE Trucking_Drivers
(
    DateTimeOperatorKey NVARCHAR(11),
    RecordDate DATETIME,
    RecordTime DATETIME,
    OperatorInitials NVARCHAR(3),
    DriverType NVARCHAR(6),
    DriverId NVARCHAR(6),
    DriverNameKey NVARCHAR(40),
    LastName NVARCHAR(20),
    FirstName NVARCHAR(20),
    MobileNumber NVARCHAR(12),
    PagerNumber NVARCHAR(12),
    EmailAddress NVARCHAR(30),
    InhouseRate NUMERIC(7,2),
    OutsideRate NUMERIC(7,2),
    ActiveFg INT,
    SubHaulerFg INT,
    DrvrMastKey NVARCHAR(12),
    WM__LastSnapshotOn DATETIME,
    WM__DeletedOn DATETIME
);
```

**Comment by michaelachrisco** [comment]
In Payroll, the department id would be joined. Where is the department id in grossman?  Or do we set that within grossman?

**Comment by josephbridgwaterrowe** [comment]
It's derived from the movement code.

**Comment by michaelachrisco** [comment]
Ok I found movement code within MovementTypes thanks.

**Comment by michaelachrisco** [comment]
I am trying to find the business logic that joins the MovementTypes and Trucking_Drivers. DR is Company Drivers but I am not certain of the movement code.

**Comment by josephbridgwaterrowe** [comment]
I believe that it happens during a load data rake task. It resolves the department id's when importing the driver commissions from CSV (of course this :hankey: is going to go away).

**Comment by michaelachrisco** [comment]
Well thats good :+1: 

Hmm...so do I need to set this to null? What query generates the department id ATM?

**Comment by josephbridgwaterrowe** [comment]
I'm not sure I understand in regard to which query generates the department id?

**Comment by michaelachrisco** [comment]
All columns that I need for drivers exists within Trucking_Drivers except the department id. I am wondering what query joins the drivers with the movement code to produce the department id.

**Comment by michaelachrisco** [comment]
As per our conversation:
Department ID comes from rake task. Add operations done by rake task into gman services to generate the Department ID.

**Comment by josephbridgwaterrowe** [comment]
I would do this in payroll since gman services have no knowledge of those departments, just the movement type.

**Comment by michaelachrisco** [comment]
Ok sounds good. I was thinking of using services to deal with the logic but if we want to keep payroll generating the department Id on the fly, then I can move the rake task methods into the interactor.

**Comment by josephbridgwaterrowe** [comment]
Let me edit my previous comment in payroll.
