### ISSUE TITLE
Deploy permission denied

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#39]
```cap production deploy```
...
```
INFO [d6f4057a] Running /usr/bin/env mkdir -p /home/gman/www/shared /home/gman/www/releases as gmanservices@gman-services.westernmilling.com
DEBUG [d6f4057a] Command: /usr/bin/env mkdir -p /home/gman/www/shared /home/gman/www/releases
DEBUG [d6f4057a] 	mkdir: cannot create directory ‘/home/gman’
DEBUG [d6f4057a] 	: Permission denied
DEBUG [d6f4057a] 	mkdir: cannot create directory ‘/home/gman’: Permission denied
```

I can go and create the folder automatically but what makes me nervous is the fact that the deploy does not have permissions.

**Comment by michaelachrisco** [comment]
cap deploys only when the rails env is production.
Even with the fix here: 
https://github.com/westernmilling/gman-services/commit/d92b24c55f84df802437cb96f46705cd2e4288dc

I believe this is a non-issue.

**Comment by josephbridgwaterrowe** [comment]
I assume this was resolved when you used the correct username in the deploy configuration?
