### ISSUE TITLE
Octopus does not generate schema.rb correctly

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#6]
Octopus currently does not generate the schema.rb when a rake db:migrate occurs. Only migrations related to the database name in database.yml will load on the schema.rb

Solutions include:
* schema folder with multi-schema for each shard and generate schema per shard. 
* monkey patch/rake task to create custom master schema file with all shards represented.

**Comment by michaelachrisco** [comment]
This may be something that we look into with other applications: https://github.com/eagletmt/switch_point

**Comment by josephbridgwaterrowe** [comment]
Certainly.

**Comment by josephbridgwaterrowe** [comment]
I've changed the way we connect to Grossman now so this can be closed.
