### ISSUE TITLE
Add Schema Plus gem

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/gman-services#9]
We wish to add the Schema Plus gem instead of generating the SQL views manually. 

Schema Plus gem + Octopus do not generate the schema.rb file correctly together. 
Related #6

**Comment by josephbridgwaterrowe** [comment]
Due to recent changes, Octopus is not a consideration here.

**Comment by josephbridgwaterrowe** [comment]
Not sure if this is necessary or desired anymore, closing for now.
